# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=200)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(default='to date', max_length=100)),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(default=uuid.uuid4, editable=False, max_length=200)),
                ('created', models.IntegerField(default=0)),
                ('expire', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('salt', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('created', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('organisation', models.CharField(blank=True, default='Jobonics', max_length=200)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('marital_status', models.CharField(max_length=50)),
                ('dob', models.IntegerField(default=0)),
                ('nationality', models.CharField(default='Kenyan', max_length=50)),
                ('personal_statement', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('skills', models.TextField()),
                ('hobbies', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicUsers.User')),
            ],
            options={
                'ordering': ('dob',),
            },
        ),
        migrations.AddField(
            model_name='loginsession',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicUsers.User'),
        ),
        migrations.AddField(
            model_name='education',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicUsers.User'),
        ),
    ]
