# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicUsers', '0002_user_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.CharField(default='English', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_facebook',
            field=models.URLField(blank=True, default='https://facebook.com/', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_instagram',
            field=models.URLField(blank=True, default='https://instagram.com/', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_linkedin',
            field=models.URLField(blank=True, default='https://linkedin.com/', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_twitter',
            field=models.URLField(blank=True, default='https://twitter.com/', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, default='https://website.com/', max_length=100, null=True),
        ),
    ]
