# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicUsers', '0003_auto_20171125_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherQualifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qualification_title', models.CharField(max_length=250)),
                ('place_acquired', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('update_history', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_job', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('update_history', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('start_date',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('date_created',)},
        ),
        migrations.RemoveField(
            model_name='education',
            name='end',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.AddField(
            model_name='education',
            name='certification',
            field=models.CharField(default='Certificate', max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='course_name',
            field=models.CharField(default='Course Title', max_length=250),
        ),
        migrations.AddField(
            model_name='education',
            name='current_level',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='education',
            name='update_history',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='update_history',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='update_history',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicUsers.User'),
        ),
        migrations.AddField(
            model_name='otherqualifications',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicUsers.User'),
        ),
    ]
