# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicUsers', '0004_auto_20171125_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('user_id',)},
        ),
        migrations.AlterModelOptions(
            name='otherqualifications',
            options={'ordering': ('user_id',)},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('user_title',)},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ('user_id',)},
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation',
        ),
    ]
