# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicUsers', '0005_auto_20171125_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='jobseeker', max_length=50),
        ),
    ]
