# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicUsers', '0006_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, default='Other', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='languages',
            field=models.CharField(blank=True, default='English', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(blank=True, default='Kenyan', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_statement',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_facebook',
            field=models.URLField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_instagram',
            field=models.URLField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_linkedin',
            field=models.URLField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_twitter',
            field=models.URLField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, default='', max_length=100, null=True),
        ),
    ]
