# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicUsers', '0008_user_global_login_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='global_login_key',
        ),
        migrations.AddField(
            model_name='user',
            name='linked_in_uid',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
