# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicUsers', '0010_auto_20171125_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nationality',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='Kenya', max_length=50, null=True),
        ),
    ]
