# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicUsers', '0011_auto_20171125_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
