# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicUsers', '0012_auto_20171125_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
