# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicUsers', '0013_auto_20171126_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherQualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qualification_title', models.CharField(max_length=250)),
                ('place_acquired', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('update_history', models.TextField(blank=True, default='', null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicUsers.User')),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
        migrations.RemoveField(
            model_name='otherqualifications',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='OtherQualifications',
        ),
    ]
