# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=250)),
                ('location', models.URLField(max_length=250)),
                ('job_type', models.URLField(max_length=250)),
                ('salary', models.URLField(max_length=250)),
                ('posted', models.URLField(max_length=250)),
                ('company_logo', models.URLField(max_length=250)),
                ('company_link', models.URLField(max_length=250)),
                ('company_name', models.URLField(max_length=250)),
                ('job_function', models.URLField(max_length=250)),
                ('description', models.URLField(max_length=250)),
                ('open', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
